### ISSUE TITLE
Setting default value ?

### ISSUE THREAD

**Issue by nicolashardy** [seeppp/NapySlider#9]
Hello,

How can I set a default value for NapySlider ? 

What I tried to do is 

    func setSliderPointsToZero() {
        let allSliders = [myNapySlider1, myNapySlider2,]
        
        for slider in allSliders {
            getLabelsInView(view: slider!).first?.text = "0"
        }
        
    }

    func getLabelsInView(view: UIView) -> [UILabel] {
        var results = [UILabel]()
        for subview in view.subviews as [UIView] {
            if let labelView = subview as? UILabel {
                results += [labelView]
            } else {
                results += getLabelsInView(view: subview)
            }
        }
        return results
    }

but it doesn't work :(

Thank you for your work
Regards

**Comment by seeppp** [comment]
Hi,

Currently, there is no property for the default value. Define ```min``` and ```max``` value and move the slider with the ```handlePosition```property.

```
napySlider.min = 0
napySlider.max = 10
napySlider.step = 2

let myDefaultPositon = 4
```
```
func moveSliderToDefaultPosition() {
    napySlider.handlePosition = myDefaultPosition
}
```

**Comment by nicolashardy** [comment]
Thank you !
